### ISSUE TITLE
make star macro work with CTEs

### ISSUE THREAD

**Issue by foundinblank** [fishtown-analytics/dbt-utils#118]
So the star macro works great - but only with tables or views. It won't work for CTEs referenced within the same data model (.sql file). 

@drewbanin's two ideas: 
> 1. executed the subquery with `limit 0`, inspecting the returned columns
> 2. creating a view, inspecting the resulting columns
>
> neither of those sound super appealing to me though :confused:

Michael Kaminsky's idea:
> DBT _could_ create a view with limit 0, inspect the catalog, and then drop the view

**Comment by drewbanin** [comment]
@foundinblank we'd need to make some pretty substantial changes in dbt core to support something like this! While I'm happy to leave this issue open to track the feature request, it's also not something that's prioritized for us in the near future.

Happy to chat about potential implementation here if you're interested, but really, the operative place for the issue is probably dbt-core i think

**Comment by foundinblank** [comment]
phew, that serious? 😅 haha. okay, i'll copy/paste it over to dbt-core. don't expect this to get worked on anytime soon, just filing it for posterity.

**Comment by luutuankiet** [comment]
If this helps I wrote a basic macro over here, hopefully this keeps the ball rolling!

https://github.com/dbt-labs/dbt-utils/issues/996#issuecomment-2707127818
