### ISSUE TITLE
Star macro does not work with a relation reference

### ISSUE THREAD

**Issue by botchniaque** [fishtown-analytics/dbt-utils#159]
I would like to use star macro for my _base_ models which reference a `source` table. When I pass a relation object as a `from` argument to `star` macro, I am getting an error

```
 dbt run -m test
Running with dbt=0.14.0
Encountered an error:
Compilation Error in model test (models/example/test.sql)
  Macro star expected a Relation but received the value: None

  > in macro _is_relation (macros/cross_db_utils/_is_relation.sql)
  > called by macro star (macros/sql/star.sql)
  > called by model test (models/example/test.sql)
```

steps to reproduce:
```
dbt init test
cd test
```

create `models/example/schema.yml` file:
```
version: 2

sources:
  - name: my_schema
    tables:
      - name: test
```

create `models/example/test.sql` file:
```
SELECT
    {%- set rel = adapter.get_relation(
      database=target.database,
      schema='my_schema',
      identifier="test") -%}

    {{ dbt_utils.star(from=rel) }}
FROM {{ source('my_schema', 'test') }}

```

Create `packages.yml` file:

```
packages:
  - package: fishtown-analytics/dbt_utils
    version: '0.2.1'

```

in Redshift create a source table:
```
create schema my_schema;
create table my_schema.test as select 1 as id;
```

run dbt:

```
dbt deps 
dbt run -m test
```

**Comment by drewbanin** [comment]
Hey @botchniaque - the `adapter.get_relation()` method will try to find the specified relation in the database, returning it if it exists. If the relation _does not exist_ in the database, then `adapter.get_relation()` will return `None`.

You have two options here:
 - figure out why `get_relation` doesn't find your relation. This might be an issue with quoting, depending on your database
 - use [api.Relation.create()](https://docs.getdbt.com/docs/api-variable#section-relation) instead of `adapter.get_relation()`. The `api.Relation.create` method will generate a new Relation object that you can pass to the `star` macro. My guess is that you'll still encounter an error around a missing / incorrectly quoted identifier, but it will probably be more helpful than the one you're seeing here.

Just curious: which database are you using?

**Comment by botchniaque** [comment]
I am using Redshift - my relation does not contain any special characters, so I'd be very surprised if there was some quoting problem. 

I'll check your suggestion - thanks

**Comment by botchniaque** [comment]
Sorry for the late reply - indeed using `api.Relation.create()` helps - now I can do `star` on my sources! thanks


```
SELECT
    {%- set rel = api.Relation.create(
      database=target.database,
      schema='my_schema',
      identifier="test") -%}

    {{ dbt_utils.star(from=rel) }}
FROM {{ source('my_schema', 'test') }}

```

**Comment by drewbanin** [comment]
Thanks for the update!
