### ISSUE TITLE
support searching model names in `get_tables_by_prefix` 

### ISSUE THREAD

**Issue by mike-weinberg** [fishtown-analytics/dbt-utils#204]
the introduction of sources made `get_tables_by_prefix` kind of non-idiomatic, because not only is it implicit, it is implicitly hard-referencing (actual relation names) something which could be soft-referenced (via ref or source expressions). 

in addition, since the naming convention of raw/source tables is often not within the control of the data team, it's possible that prefix is not a viable strategy for pattern matching. however source model names *are* within the control of the data team, and so source names can be constructed such that a prefix pattern could be adequate for in more cases. 

For example, we have a schema of tables for various attributes of a certain kind of iot device, subdivided by region and the naming convention is something like `{{region}}{{entity}}` so like perhaps `eastuswidgets` -- a terrible name, of course, but it isn't **totally** contrived.  

Since we want to union all the widgets tables, we'd really need to match by suffix in this case. but if I could look up the source models instead of the raw relation names, I could make sure to name the source for that relation `widgets_us_east`, and so if I could search those with `get_tables_by_prefix` (or perhaps a new macro `get_models_by_prefix` ... or `get_models_by_pattern`) then I would now be able to use the `union_tables` (_née, union MODELS!_) macro, which is deterministic, unit testable / lintable, faster, and preserves lineage info. 

I am considering a second issue (not yet authored / linked) for declarative sources which _would_ need arbitrary pattern matching in order to deal with the arbitrary naming conventions of source tables, although _that_ might not be idiomatic, since columns generally should be explicitly included in yml files...

Side note: the term `tables` used frequently in dbt utils is kinda inconsistent with the seemingly dbt-preferred idiom of `relations`

**Comment by clrcrl** [comment]
Hey @mike-weinberg.

Not sure if you saw this but in the readme we have:
> #### get_relations_by_prefix
>> This replaces the `get_tables_by_prefix` macro. Note that the `get_tables_by_prefix` macro will be deprecated in a future release of this package.

**Comment by mike-weinberg** [comment]
> Hey @mike-weinberg.
> 
> Not sure if you saw this but in the readme we have:
> 
> > #### get_relations_by_prefix
> > > This replaces the `get_tables_by_prefix` macro. Note that the `get_tables_by_prefix` macro will be deprecated in a future release of this package.
> 
> We also changed `union_tables` to be `union_relations`

=D

**Comment by clrcrl** [comment]
I've reread this a few times, and I'm still not sure what you're asking for here. I'll do my best to explain it back:

- `get_tables_by_prefix` should use relations --> it does (see above)
- Instead, you'd like a `get_models_by_prefix` macro, where it selects based on the model matching pattern, something like:
```
{{ get_models_by_prefix('widgets_') }}
```
Which would return: `[ref('widgets_us_east'), ref('widgets_us_west')]`

So that you can:
```
{% set my_models = get_models_by_prefix('widgets_') %}
{{ union_relations(my_models) }}
```

I think this is a valid request, but I suspect it is outside of the scope of utils:
- First, we need an interface in dbt to [dynamically reference models](https://github.com/fishtown-analytics/dbt/issues/1212).
- Then, I think we'd need a selector that does partial name matching
(going to cc @drewbanin to confirm my understand of dbt internals here)

As an aside, we've done some hackery in the past to pattern match sources, and return a list of source Relations. The tradeoff was that we lost the arrows in the DAG. I think it works for sources, but not for models because models would lose their dependencies (again, Drew to confirm here).

Check out [this article](https://discourse.getdbt.com/t/unioning-identically-structured-data-sources/921), especially:
```
{% macro get_sources(source_prefix, table_name) %}
    {% set sources = [] %}
    {% if execute %}
    {% for node_name, node in graph.nodes.items() %}
        {% if node.resource_type == 'source' and node.name == table_name and node.source_name.startswith(source_prefix) %}
            {% set new_source = source(node.source_name, node.name) %}
            {% do sources.append(new_source) %}
        {% endif %}
    {% endfor %}
    {% do return(sources) %}
    {% endif %}
{% endmacro %}
```

**Comment by mike-weinberg** [comment]
@clrcrl thanks for humoring me on this! This explanation is perfect, and the linked issue is extremely similar, so I think we can close this as a duplicate, or we can focus on the other half of the problem in this case, which deals with the fact that a prefix may not always be sufficient for pattern matching. 

How do you feel about shifting directions to a discussion of regex-based pattern matching against information_schema.tables as an (additional) alternative to prefix-only matching? eg `get_relations_by_regex` or similar.

**Comment by mike-weinberg** [comment]
closing because of disruptions to docs this would cause. Maybe if DBT core changes the compilation process, as you were saying, then it would be worth addressign @clrcrl . thanks for the information!
