### ISSUE TITLE
Bump require-dbt-version to 0.16.0

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt-utils#210]
- Per the [release notes](https://github.com/fishtown-analytics/dbt-utils/releases/tag/0.3.0), the 0.3.0 release requires dbt version >= 0.16.0
- We should update `require-dbt-version` [here](https://github.com/fishtown-analytics/dbt-utils/blob/master/dbt_project.yml#L4) accordingly

**Comment by clrcrl** [comment]
So uh, it turns out that the release notes are incorrect, the require-dbt-version parameter is correct.

This version increase was required since we added the `warn` exception to this package, which was added in `0.15.1` ([changelog](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/CHANGELOG.md#dbt-0151-january-17-2020)).

I've opted to update the release notes, rather than reduce the dbt version range. Do you buy that? (If not, feel free to re-open) I could definitely be convinced that increasing to 0.16.0 is just good practice
